apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: upstream-rabbit-new
spec:
  service:
    type: ClusterIP
  replicas: 3
  rabbitmq:
    additionalPlugins:
      - rabbitmq_stream
      - rabbitmq_prometheus
      - rabbitmq_schema_definition_sync
      - rabbitmq_schema_definition_sync_prometheus # optional
      - rabbitmq_federation
      - rabbitmq_federation_management
      - rabbitmq_stream_management
      - rabbitmq_shovel
      - rabbitmq_shovel_management
      # - rabbitmq_standby_replication
    # additionalConfig: |
    #   schema_definition_sync.operating_mode = upstream
    #   standby.replication.operating_mode = upstream
    #   # message stream retention limit (can either be size or time based)
    #   standby.replication.retention.size_limit.messages = 5000000000
      # standby.replication.retention.time_limit.messages = 12h
      # schema_definition_sync.ssl_options.certfile              = /etc/rabbitmq-tls/tls.crt
      # schema_definition_sync.ssl_options.keyfile               = /etc/rabbitmq-tls/tls.key
      # schema_definition_sync.ssl_options.verify                = verify_none
      # schema_definition_sync.ssl_options.fail_if_no_peer_cert  = false
